name: Terraform Module Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    name: Create Version Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tag
        id: get_version
        run: echo "VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo 'v0.0.0')" >> $GITHUB_ENV

      - name: Determine next version
        id: bump_version
        run: |
          VERSION=${{ env.VERSION }}
          echo "Current Version: $VERSION"
          IFS='.' read -r MAJOR MINOR PATCH <<<"${VERSION#v}"
          if [[ "${{ github.event.head_commit.message }}" == *"major:"* ]]; then
            ((MAJOR++))
            MINOR=0
            PATCH=0
          elif [[ "${{ github.event.head_commit.message }}" == *"minor:"* ]]; then
            ((MINOR++))
            PATCH=0
          else
            ((PATCH++))
          fi
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
          echo "New Version: $NEW_VERSION"

      - name: Create new tag
        run: |
          git config --global user.name "tfversioning"
          git config --global user.email "tfversionings@github.com"
          git tag ${{ env.NEW_VERSION }}
          git push origin ${{ env.NEW_VERSION }}
